#!/bin/bash

if [ ${UID} -ne 0 ]
then
echo
ehco "You need root access for this command"
echo
exit 1
fi

## check number of  processors

c=`nproc`

if [  $ {c} -eq 1]
	echo "This server is very small"
	exit 2
fi
